name: deploy-api-docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    container:
      image: swift:5.7
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build site
      run: swift generate-api-docs.swift
    - name: Configure AWS Credentials
      id: cred
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.API_DOCS_DEPLOYER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.API_DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-2'
    - name: Depoly to AWS CloudFormation
      id: clouddeploy
      uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
      with:
        name: vapor-api-docs
        template: stack.yaml
        no-fail-on-empty-changeset: '1'
        parameter-overrides: >-
          BucketName=vapor-api-docs-site,
          SubDomainName=api,
          HostedZoneName=vapor.codes,
          AcmCertificateArn=${{ secrets.API_DOCS_CERTIFICATE_ARN }}
      if: steps.cred.outcome == 'success'
    - name: Deploy to S3
      id: s3deploy
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'vapor-api-docs-site'
        AWS_ACCESS_KEY_ID: ${{ secrets.API_DOCS_DEPLOYER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.API_DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: 'public'
      if: steps.clouddeploy.outcome == 'success'
    - name: Invalidate CloudFront
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/*'
        AWS_ACCESS_KEY_ID: ${{ secrets.API_DOCS_DEPLOYER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.API_DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
        DISTRIBUTION_ID: ${{ secrets.VAPOR_API_DOCS_DISTRIBUTION_ID }}
